import "@/styles/globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";
import { BrowserUIProviders } from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      dir="ltr"
      className="no-scrollbar scroll-smooth antialiased focus:scroll-auto"
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-dvh bg-background font-sans overflow-x-hidden`}
      >
        <BrowserUIProviders>
          <div vaul-drawer-wrapper="">{children}</div>
        </BrowserUIProviders>
      </body>
    </html>
  );
}
